services:
  db:
    image: ghcr.io/tursodatabase/libsql-server:latest
    platform: linux/amd64
    ports:
      - 8080
      - 5001
    environment:
      - SQLD_NODE=primary
      - SQLD_AUTH_JWT_KEY=s03oSvyzUG_4fmII2kLOM49tDSnNS8Bjuu4Js-Y0A8Q
    networks:
      - dokploy-network
    volumes:
      - ../files/libsql:/var/lib/sqld

networks:
  dokploy-network:
    external: true
